---
services:
  db:
    image: docker.io/library/mariadb:latest
    container_name: python-rest-api-db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ${PWD}/app/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    environment:
      - MARIADB_PASSWORD=password
      - MARIADB_USER=user
      - MARIADB_DATABASE=python_rest_api
      - MARIADB_ROOT_PASSWORD=password

  redis:
    image: docker.io/library/redis:alpine
    container_name: python-rest-api-redis

  api:
    image: docker.io/toleksa/python-rest-api:latest
    container_name: python-rest-api
    build: .
    ports:
      - 5000:5000
    environment:
      - DB_PASS=password
      - DB_USER=user
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  prometheus:
    image: bitnami/prometheus:latest
    container_name: python-rest-api-prometheus
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml:Z
    ports:
      - 9090:9090

