---
version: "3"
services:
  db:
    image: docker.io/library/mariadb:latest
    container_name: python-rest-api-db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ${PWD}/app/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    environment:
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_USER=${DB_USER}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}

  redis:
    image: docker.io/library/redis:alpine
    container_name: python-rest-api-redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  api:
    image: docker.io/toleksa/python-rest-api:latest
    container_name: python-rest-api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JAEGER_HOST=${JAEGER_HOST}
      - JAEGER_PORT=${JAEGER_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  statsd:
    image: prom/statsd-exporter:latest
    container_name: python-rest-api-statsd
    ports:
      - "9125:9125"
      - "9102:9102"

  prometheus:
    image: bitnami/prometheus:latest
    container_name: python-rest-api-prometheus
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml:Z
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}

  grafana:
    image: grafana/grafana:latest
    container_name: python-rest-api-grafana
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    volumes:
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning:Z
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL}

  www:
    image: docker.io/toleksa/python-rest-api-www:latest
    container_name: python-rest-api-www
    build: www/
    ports:
      - ${WWW_PORT}:${WWW_PORT}
    environment:
      #- ENV_API_URL=http://${HOSTNAME}:5000
      - WWW_PORT=${WWW_PORT}

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: python-rest-api-jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      #TODO: 6831 - for sending traces, 16686 - www -> are other ports needed?
      - ${JAEGER_PORT}:6831/udp
      - 5775:5775/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

