services:
  test:
    image: docker.io/toleksa/python-rest-api-test:latest
    build: tests/integration
    container_name: python-rest-api-test
    command: echo "pytest -o cache_dir=/tmp/.pytest_cache --junit-xml=test_integration_result.xml /pytest/test_integration.py" > run.sh ; chmod +x run.sh ; cat
    volume:
      - ${PWD}/tests/integration/test_integration.py:/pytest/test_integration.py
 
