---
version: "3"
services:
  test:
    image: docker.io/toleksa/python-rest-api-test:latest
    build:
      context: .
      dockerfile: tests/integration/Dockerfile
    container_name: python-rest-api-test
    entrypoint: tail -f /dev/null
    volumes:
      - ${PWD}/tests/integration:/pytest:Z
    environment:
      - API_URL=${API_URL}
      - WWW_URL=${WWW_URL}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
  perf:
    image: blazemeter/taurus:latest
    container_name: python-rest-api-perf
    entrypoint: ''
    command: sleep infinity
    volumes:
      - ${PWD}/tests/performance:/bzt-configs:Z
    environment:
      - API_URL=${API_URL}
  db:
    ports:
      - ${DB_PORT}:${DB_PORT}
  redis:
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  www:
    environment:
      - ENV_API_URL=${API_URL}

 
