services:
  test:
    image: docker.io/toleksa/python-rest-api-test:latest
    build:
      context: .
      dockerfile: tests/integration/Dockerfile
    container_name: python-rest-api-test
    entrypoint: tail -f /dev/null
    volumes:
      - ${PWD}/tests/integration/test_integration.py:/pytest/test_integration_mount.py:Z
    environment:
      - API_URL=http://api:5000
  db:
    ports:
      - 3306:3306
  redis:
    ports:
      - 6379:6379
 
