---
services:
  db:
    image: docker.io/library/mariadb:latest
    container_name: python-rest-api-db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ${PWD}/app/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    environment:
      - MARIADB_PASSWORD=password
      - MARIADB_USER=user
      - MARIADB_DATABASE=python_rest_api
      - MARIADB_ROOT_PASSWORD=password

  redis:
    image: docker.io/library/redis:alpine
    container_name: python-rest-api-redis

  api:
    image: docker.io/toleksa/python-rest-api:latest
    container_name: python-rest-api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - DB_PASS=password
      - DB_USER=user
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  prometheus:
    image: bitnami/prometheus:latest
    container_name: python-rest-api-prometheus
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml:Z
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}

  grafana:
    image: grafana/grafana:latest
    container_name: python-rest-api-grafana
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    volumes:
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning:Z
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL}

  www:
    image: docker.io/toleksa/python-rest-api-www:latest
    container_name: python-rest-api-www
    build: www/
    ports:
      - ${WWW_PORT}:${WWW_PORT}
    environment:
      #- ENV_API_URL=http://${HOSTNAME}:5000
      - WWW_PORT=${WWW_PORT}

