---
services:
  db:
    image: docker.io/library/mariadb:10.10.2
    container_name: python-rest-api-db
    hostname: db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ${PWD}/../app/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    environment:
      - MARIADB_PASSWORD=password
      - MARIADB_USER=user
      - MARIADB_DATABASE=python_rest_api
      - MARIADB_ROOT_PASSWORD=password

  redis:
    image: docker.io/library/redis:7.0.5-alpine
    container_name: python-rest-api-redis
    hostname: redis

  api:
    image: docker.io/toleksa/python-rest-api:latest
    container_name: python-rest-api
    hostname: api
    ports:
      - 5000:5000
    environment:
      - DB_PASS=password
      - DB_USER=user
      - DB_HOST=db
      - REDIS_HOST=redis

