---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
data:
  database_url: mariadb-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-statefulset
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: mariadb-db-volume
          persistentVolumeClaim:
            claimName: mariadb-pvc
        - name: mariadb-init
          configMap: 
            name: mariadb-init
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mariadb-db-volume
            mountPath: "/var/lib/mysql"
          - name: mariadb-init
            mountPath: "/docker-entrypoint-initdb.d/init.sql"
            subPath: init.sql
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-root-password
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-password
        - name: MARIADB_DATABASE
          value: python_rest_api
        - name: MARIADB_USER
          value: python-rest-api
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

