---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-rest-api
  labels:
    app: python-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-rest-api
  template:
    metadata:
      labels:
        app: python-rest-api
    spec:
      containers:
      - name: python-rest-api
        image: toleksa/python-rest-api
        ports:
        - name: http
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: DB_USER
          value: python-rest-api
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-password
        - name: API_PORT
          value: "5000"
        - name: DB_HOST
          value: "mariadb"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "python_rest_api"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: STATSD_HOST
          value: "statsd"
        - name: STATSD_PORT
          value: "9125"
        - name: JAEGER_HOST
          value: "jaeger"
        - name: JAEGER_PORT
          value: "6831"

---
apiVersion: v1
kind: Service
metadata:
  name: python-rest-api
spec:
  selector:
    app: python-rest-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-rest-api
spec:
  ingressClassName: "nginx"
  rules:
  - host: python-rest-api.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-rest-api
            port:
              number: 5000
