---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-rest-api-deployment
  labels:
    app: python-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-rest-api
  template:
    metadata:
      labels:
        app: python-rest-api
    spec:
      containers:
      - name: python-rest-api
        image: toleksa/python-rest-api
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: python-rest-api-service
spec:
  selector:
    app: python-rest-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-rest-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: api.v1.kube.ac
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-rest-api-service
            port:
              number: 5000
