apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-rest-api-redis
  namespace: argocd
spec:
  destination:
    namespace: python-rest-api
    server: 'https://kubernetes.default.svc'
  project: python-rest-api
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '17.3.16'
    chart: redis
    helm:
      values: |
        service:
          type: ClusterIP
          port: 6379
        architecture: standalone
        auth:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
