apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-rest-api
  namespace: argocd
spec:
  destination:
    namespace: python-rest-api
    server: 'https://kubernetes.default.svc'
  project: python-rest-api
  source:
    repoURL: 'https://github.com/toleksa/python-rest-api'
    targetRevision: HEAD
    path: 'helm/python-rest-api'
    helm:
      values: |
        replicaCount: 3
        ingress:
          enabled: true
          className: ""
          annotations: {}
            # kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
          hosts:
            - host: "python-rest-api.{{ .Values.domain}}"
              paths:
                - path: /
                  pathType: Prefix
          tls: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
