{
 "title": "python-rest-api",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "status_code rate /s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(python_rest_api_responses_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses rate /s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(python_rest_api_responses_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "error ratio %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "100 * (sum(rate(python_rest_api_responses_total{status_code!~\"2..|3..\"}[1m])) by (instance) / sum(rate(python_rest_api_responses_total[1m])) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "error rate [10m]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(python_rest_api_responses_total{status_code=~\"2..|3..\"}[10m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(python_rest_api_responses_total{status_code!~\"2..|3..\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}