apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-rest-api-main
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/toleksa/python-rest-api'
    targetRevision: HEAD
    path: 'argo'
    helm:
      values: |
        metallb:
          pools:
          - name: default
            protocol: layer2
            addresses:
            - $METALLB_ADDRESSES
            avoid-buggy-ips: true
        argocd:
          server:
            ingress:
              enabled: true
        domain: 'kube.ac'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
