domain: example.com

longhorn:
  defaultClassReplicaCount: 1
  ingress:
    enabled: false

metallb:
  pools: []

argocd:
  installCRDs: false
  global:
    image:
      tag: v2.1.3
  server:
    ingress:
      enabled: true

