apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-rest-api.fullname" . }}
  labels:
    {{- include "python-rest-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "python-rest-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "python-rest-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "python-rest-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: DB_USER
            value: python-rest-api
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: python-rest-api-mariadb
                key: mariadb-password
          - name: DB_DATABASE
            value: python_rest_api
          - name: API_PORT
            value: "5000"
          - name: DB_HOST
            value: python-rest-api-mariadb
          - name: DB_PORT
            value: "3306"
          - name: REDIS_HOST
            value: python-rest-api-redis-master
          - name: REDIS_PORT
            value: "6379"
          - name: STATSD_HOST
            value: python-rest-api-statsd-prometheus-statsd-exporter
          - name: STATSD_PORT
            value: "9125"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
