apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "python-rest-api.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "python-rest-api.fullname" . }}
      app.kubernetes.io/name: {{ include "python-rest-api.fullname" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - interval: 30s
    port: "http"
    path: /metrics

