{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "python-rest-api.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "python-rest-api.fullname" . }}
      app.kubernetes.io/name: {{ include "python-rest-api.fullname" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - interval: 30s
    port: "http"
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ include "python-rest-api.fullname" . }}-statsd"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "python-rest-api-statsd"
      app.kubernetes.io/name: "prometheus-statsd-exporter"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - interval: 30s
    port: "http"
    path: /metrics
{{- end }}
