grafana:
  adminPassword: prom-operator
  ingress:
    enabled: true
    hosts:
    - "grafana.example.com"

prometheus:
  ingress:
    enabled: true
    hosts:
    - "prometheus.example.com"
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
